// Auto-generated from backend/app/brsr_datapoints.py — 337 BRSR datapoints
// DO NOT EDIT MANUALLY

export interface BRSRField {
  id: string;
  label: string;
  type: "text" | "number" | "textarea" | "select" | "email" | "url";
  required: boolean;
  options?: string[];
  core?: boolean;
  leadership?: boolean;
}

export interface BRSRSubsection {
  id: string;
  name: string;
  fields: BRSRField[];
}

export interface BRSRSection {
  name: string;
  subsections: BRSRSubsection[];
}

export const SECTIONS: Record<string, BRSRSection> = {
  section_a: {
    name: "Section A — General Disclosures",
    subsections: [
      {
        id: "details_of_entity",
        name: "I. Details of the Listed Entity",
        fields: [
          { id: "A.I.1", label: "Corporate Identity Number (CIN)", type: "textarea", required: true, core: true },
          { id: "A.I.2", label: "Name of the Listed Entity", type: "textarea", required: true, core: true },
          { id: "A.I.3", label: "Year of incorporation", type: "text", required: true },
          { id: "A.I.4", label: "Registered office address", type: "textarea", required: true },
          { id: "A.I.5", label: "Corporate address", type: "textarea", required: true },
          { id: "A.I.6", label: "E-mail", type: "textarea", required: true },
          { id: "A.I.7", label: "Telephone", type: "textarea", required: true },
          { id: "A.I.8", label: "Website", type: "textarea", required: true },
          { id: "A.I.9", label: "Financial year for which reporting is being done", type: "text", required: true, core: true },
          { id: "A.I.10", label: "Name of Stock Exchange(s) where shares are listed", type: "textarea", required: true },
          { id: "A.I.11", label: "Paid-up Capital (INR)", type: "number", required: true },
          { id: "A.I.12", label: "Name and contact details of person for BRSR queries", type: "textarea", required: true },
          { id: "A.I.13", label: "Reporting boundary - Standalone or Consolidated", type: "select", required: true, core: true, options: ["Standalone", "Consolidated"] },
          { id: "A.I.14", label: "Name of assurance provider", type: "textarea", required: false, core: true },
          { id: "A.I.15", label: "Type of assurance obtained (limited/reasonable)", type: "select", required: false, core: true, options: ["Limited Assurance", "Reasonable Assurance", "Not Applicable"] },
        ],
      },
      {
        id: "products_services",
        name: "II. Products/Services",
        fields: [
          { id: "A.II.1", label: "Details of business activities (accounting for 90% of turnover)", type: "textarea", required: true },
          { id: "A.II.2", label: "Products/Services sold (accounting for 90% of turnover)", type: "textarea", required: true },
          { id: "A.II.3", label: "NIC codes for products/services", type: "textarea", required: true },
        ],
      },
      {
        id: "operations",
        name: "III. Operations",
        fields: [
          { id: "A.III.1", label: "Number of locations - Plants (National)", type: "number", required: true },
          { id: "A.III.2", label: "Number of locations - Plants (International)", type: "number", required: true },
          { id: "A.III.3", label: "Number of locations - Offices (National)", type: "number", required: true },
          { id: "A.III.4", label: "Number of locations - Offices (International)", type: "number", required: true },
          { id: "A.III.5", label: "Markets served - Number of States/UTs", type: "number", required: true },
          { id: "A.III.6", label: "Markets served - Number of Countries", type: "number", required: true },
          { id: "A.III.7", label: "Contribution of exports as % of total turnover", type: "number", required: true },
          { id: "A.III.8", label: "Types of customers", type: "textarea", required: true },
          { id: "A.III.9", label: "Number of locations - Total (National)", type: "number", required: true },
          { id: "A.III.10", label: "Number of locations - Total (International)", type: "number", required: true },
        ],
      },
      {
        id: "employees",
        name: "IV. Employees",
        fields: [
          { id: "A.IV.1", label: "Total employees - Permanent - Male", type: "number", required: true, core: true },
          { id: "A.IV.2", label: "Total employees - Permanent - Female", type: "number", required: true, core: true },
          { id: "A.IV.3", label: "Total employees - Permanent - Total", type: "number", required: true, core: true },
          { id: "A.IV.4", label: "Total employees - Other than Permanent - Male", type: "number", required: true },
          { id: "A.IV.5", label: "Total employees - Other than Permanent - Female", type: "number", required: true },
          { id: "A.IV.6", label: "Total employees - Other than Permanent - Total", type: "number", required: true },
          { id: "A.IV.7", label: "Total workers - Permanent - Male", type: "number", required: true, core: true },
          { id: "A.IV.8", label: "Total workers - Permanent - Female", type: "number", required: true, core: true },
          { id: "A.IV.9", label: "Total workers - Permanent - Total", type: "number", required: true, core: true },
          { id: "A.IV.10", label: "Total workers - Other than Permanent - Male", type: "number", required: true },
          { id: "A.IV.11", label: "Total workers - Other than Permanent - Female", type: "number", required: true },
          { id: "A.IV.12", label: "Total workers - Other than Permanent - Total", type: "number", required: true },
          { id: "A.IV.13", label: "Differently abled Employees - Permanent (Male/Female/Total)", type: "textarea", required: true },
          { id: "A.IV.14", label: "Differently abled Employees - Other than Permanent (Male/Female/Total)", type: "textarea", required: true },
          { id: "A.IV.15", label: "Differently abled Workers - Permanent (Male/Female/Total)", type: "textarea", required: true },
          { id: "A.IV.16", label: "Differently abled Workers - Other than Permanent (Male/Female/Total)", type: "textarea", required: true },
          { id: "A.IV.17", label: "Participation/Inclusion/Representation of women - Board of Directors (%)", type: "number", required: true, core: true },
          { id: "A.IV.18", label: "Participation/Inclusion/Representation of women - Key Management Personnel (%)", type: "number", required: true },
          { id: "A.IV.19", label: "Turnover rate for permanent employees - Male (current + 2 preceding FY)", type: "textarea", required: true, core: true },
          { id: "A.IV.20", label: "Turnover rate for permanent employees - Female (current + 2 preceding FY)", type: "textarea", required: true, core: true },
          { id: "A.IV.21", label: "Turnover rate for permanent workers - Male (current + 2 preceding FY)", type: "textarea", required: true, core: true },
          { id: "A.IV.22", label: "Turnover rate for permanent workers - Female (current + 2 preceding FY)", type: "textarea", required: true, core: true },
          { id: "A.IV.23", label: "Total employees (D+E) - Male", type: "number", required: true },
          { id: "A.IV.24", label: "Total employees (D+E) - Female", type: "number", required: true },
          { id: "A.IV.25", label: "Total employees (D+E) - Total", type: "number", required: true, core: true },
          { id: "A.IV.26", label: "Total workers (F+G) - Male", type: "number", required: true },
          { id: "A.IV.27", label: "Total workers (F+G) - Female", type: "number", required: true },
          { id: "A.IV.28", label: "Total workers (F+G) - Total", type: "number", required: true, core: true },
        ],
      },
      {
        id: "holding_subsidiary",
        name: "V. Holding/Subsidiary/Associates",
        fields: [
          { id: "A.V.1", label: "Names of holding/subsidiary/associate/JV companies", type: "textarea", required: true },
          { id: "A.V.2", label: "Whether business conduct/ethics policies apply to group companies", type: "select", required: true, options: ["Yes", "No"] },
        ],
      },
      {
        id: "csr_details",
        name: "VI. CSR Details",
        fields: [
          { id: "A.VI.1", label: "Whether CSR is applicable as per Section 135 of Companies Act 2013", type: "select", required: true, options: ["Yes", "No"] },
          { id: "A.VI.2", label: "Turnover (in Rs.)", type: "number", required: true },
          { id: "A.VI.3", label: "Net worth (in Rs.)", type: "number", required: true },
        ],
      },
      {
        id: "transparency",
        name: "VII. Transparency & Disclosures",
        fields: [
          { id: "A.VII.1", label: "Complaints/Grievances on any of the Principles (P1-P9) - Number filed/pending/remarks", type: "textarea", required: true },
          { id: "A.VII.2", label: "Overview of material responsible business conduct and sustainability issues", type: "textarea", required: true },
        ],
      },
    ],
  },
  section_b: {
    name: "Section B — Management & Process Disclosures",
    subsections: [
      {
        id: "policy_management",
        name: "Policy & Management",
        fields: [
          { id: "B.1", label: "Whether policy covers each principle (P1-P9)", type: "textarea", required: true },
          { id: "B.2", label: "Whether policy approved by Board (P1-P9)", type: "textarea", required: true },
          { id: "B.3", label: "Web link of each policy (P1-P9)", type: "textarea", required: true },
          { id: "B.4", label: "Whether policy has been translated into procedures/codes", type: "select", required: true, options: ["Yes", "No"] },
          { id: "B.5", label: "Whether policy extends to value chain partners", type: "select", required: true, options: ["Yes", "No"] },
          { id: "B.6", label: "National/international codes/certifications/labels adopted (mapped to principles)", type: "textarea", required: true },
          { id: "B.7", label: "Specific commitments, goals and targets set with defined timelines", type: "textarea", required: true },
          { id: "B.8", label: "Performance of entity against specific commitments/goals/targets", type: "textarea", required: true },
          { id: "B.15", label: "Reasons why entity does not consider certain Principles material to business (P1-P9)", type: "textarea", required: true },
          { id: "B.16", label: "Whether entity not at stage to formulate/implement policies on certain principles (P1-P9)", type: "textarea", required: true },
          { id: "B.17", label: "Whether entity lacks financial/human/technical resources for certain principles (P1-P9)", type: "textarea", required: true },
          { id: "B.18", label: "Whether planned to be done in next FY for certain principles (P1-P9)", type: "textarea", required: true },
        ],
      },
      {
        id: "governance",
        name: "Governance & Oversight",
        fields: [
          { id: "B.9", label: "Statement by director responsible for BR highlighting ESG challenges, targets, achievement", type: "textarea", required: true },
          { id: "B.10", label: "Details of highest authority responsible for implementation of BR policies", type: "textarea", required: true },
          { id: "B.11", label: "Whether sustainability-related decisions are considered in Board Committee meetings", type: "select", required: true, options: ["Yes", "No"] },
          { id: "B.12", label: "Details of review of NGRBCs by Board/Committee - frequency and scope", type: "textarea", required: true },
          { id: "B.13", label: "Whether independent assessment/evaluation of policies by external agency", type: "select", required: true, options: ["Yes", "No"] },
          { id: "B.14", label: "Name of external agency performing assessment", type: "textarea", required: false },
        ],
      },
    ],
  },
  section_c: {
    name: "Section C — Principle-wise Performance",
    subsections: [
      {
        id: "principle_1",
        name: "P1 — Ethics, Transparency & Accountability",
        fields: [
          { id: "C.P1.E.1", label: "Percentage of training/awareness on principles (Board of Directors)", type: "number", required: true },
          { id: "C.P1.E.2", label: "Percentage of training/awareness on principles (KMPs)", type: "number", required: true },
          { id: "C.P1.E.3", label: "Percentage of training/awareness on principles (Employees other than BoD/KMPs)", type: "number", required: true },
          { id: "C.P1.E.4", label: "Percentage of training/awareness on principles (Workers)", type: "number", required: true },
          { id: "C.P1.E.5", label: "Details of fines/penalties/punishment/award/compounding from NFRA/SEBI/regulatory/judicial", type: "textarea", required: true, core: true },
          { id: "C.P1.E.6", label: "Details of appeal/revision preferred (against fines/penalties)", type: "textarea", required: true, core: true },
          { id: "C.P1.E.7", label: "Whether entity has anti-corruption or anti-bribery policy", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P1.E.8", label: "Number of Directors/KMPs/employees against whom disciplinary action taken for bribery/corruption", type: "number", required: true },
          { id: "C.P1.E.9", label: "Number of complaints regarding conflict of interest - Directors (current FY + preceding FY)", type: "textarea", required: true },
          { id: "C.P1.E.10", label: "Number of complaints regarding conflict of interest - KMPs (current FY + preceding FY)", type: "textarea", required: true },
          { id: "C.P1.E.11", label: "Corrective action taken on fines/penalties/action in current FY", type: "textarea", required: true },
          { id: "C.P1.E.12", label: "Number of days of accounts payables (current FY + preceding FY)", type: "textarea", required: true },
          { id: "C.P1.E.13", label: "Concentration of purchases - top 10 suppliers as % of total purchases", type: "number", required: true },
          { id: "C.P1.E.14", label: "Concentration of sales - top 10 customers as % of total sales", type: "number", required: true },
          { id: "C.P1.L.1", label: "Awareness programmes conducted for value chain partners on principles", type: "textarea", required: false, leadership: true },
          { id: "C.P1.L.2", label: "Whether entity has processes to avoid/manage conflict of interest (Board/KMPs)", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P1.E.15", label: "Purchases from trading houses as % of total purchases", type: "number", required: true },
          { id: "C.P1.E.16", label: "Number of trading houses where purchases are made from", type: "number", required: true },
          { id: "C.P1.E.17", label: "Sales to dealers/distributors as % of total sales", type: "number", required: true },
          { id: "C.P1.E.18", label: "Number of dealers/distributors to whom sales are made", type: "number", required: true },
          { id: "C.P1.E.19", label: "Sales to top 10 dealers/distributors as % of total sales", type: "number", required: true },
          { id: "C.P1.E.20", label: "Purchases with related parties as % of Total Purchases (RPT)", type: "number", required: true },
          { id: "C.P1.E.21", label: "Sales to related parties as % of Total Sales (RPT)", type: "number", required: true },
          { id: "C.P1.E.22", label: "Loans & advances to related parties as % of Total Loans & advances (RPT)", type: "number", required: true },
          { id: "C.P1.E.23", label: "Investments in related parties as % of Total Investments (RPT)", type: "number", required: true },
        ],
      },
      {
        id: "principle_2",
        name: "P2 — Product Life Cycle Sustainability",
        fields: [
          { id: "C.P2.E.1", label: "R&D and capex investments for improvement in environmental aspects of products (% of turnover)", type: "number", required: true },
          { id: "C.P2.E.2", label: "R&D and capex investments for improvement in social aspects of products (% of turnover)", type: "number", required: true },
          { id: "C.P2.E.3", label: "Whether entity has procedures for sustainable sourcing", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P2.E.4", label: "Percentage of inputs sourced sustainably", type: "number", required: true, core: true },
          { id: "C.P2.E.5", label: "Describe processes in place to safely reclaim products at end of life (reuse/recycle/safe disposal)", type: "textarea", required: true },
          { id: "C.P2.E.6", label: "Whether Extended Producer Responsibility (EPR) is applicable", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P2.E.7", label: "EPR - Plastic waste collected/recycled (if applicable)", type: "number", required: true },
          { id: "C.P2.E.8", label: "EPR - E-waste collected/recycled (if applicable)", type: "number", required: true },
          { id: "C.P2.L.1", label: "Whether Life Cycle Perspective/Assessment (LCA) conducted for products", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P2.L.2", label: "Results of LCA and significant social/environmental concerns identified", type: "textarea", required: false, leadership: true },
          { id: "C.P2.L.3", label: "Recycled/reused input material to total material - by weight (%)", type: "number", required: false, core: true, leadership: true },
          { id: "C.P2.L.4", label: "Products and packaging reclaimed at end of life - Reused (MT/% of total)", type: "textarea", required: false, leadership: true },
          { id: "C.P2.L.5", label: "Products and packaging reclaimed at end of life - Recycled (MT/% of total)", type: "textarea", required: false, leadership: true },
        ],
      },
      {
        id: "principle_3",
        name: "P3 — Employee Wellbeing",
        fields: [
          { id: "C.P3.E.1", label: "Well-being measures for employees - Health insurance coverage (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.2", label: "Well-being measures for employees - Accident insurance coverage (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.3", label: "Well-being measures for employees - Maternity benefits coverage (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.4", label: "Well-being measures for employees - Paternity benefits coverage (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.5", label: "Well-being measures for employees - Day care facilities coverage (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.6", label: "Well-being measures for workers - Health/Accident/Maternity/Paternity/Day care (%)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.7", label: "Spending on measures towards well-being of employees and workers (% of total revenue)", type: "number", required: true },
          { id: "C.P3.E.8", label: "Retirement benefits (PF/Gratuity/ESI/Others) - deducted and deposited on time", type: "textarea", required: true },
          { id: "C.P3.E.9", label: "Whether premises/offices accessible to differently abled employees/workers", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.10", label: "Whether entity has an equal opportunity policy", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.11", label: "Return to work and Retention rates of permanent employees that took parental leave", type: "textarea", required: true },
          { id: "C.P3.E.12", label: "Whether mechanism for grievance redressal available for employees", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.13", label: "Whether mechanism for grievance redressal available for workers", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.14", label: "Membership of employees and workers in associations/unions (current + preceding FY)", type: "textarea", required: true },
          { id: "C.P3.E.15", label: "Training details - Health and safety measures (employees/workers by gender)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.16", label: "Training details - Skill upgradation (employees/workers by gender)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.17", label: "Performance and career development reviews - Employees (Male/Female/%)", type: "textarea", required: true },
          { id: "C.P3.E.18", label: "Performance and career development reviews - Workers (Male/Female/%)", type: "textarea", required: true },
          { id: "C.P3.E.19", label: "Whether occupational health and safety management system has been implemented", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P3.E.20", label: "Details of safety incidents - LTIFR (Employees/Workers)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.21", label: "Details of safety incidents - Fatalities (Employees/Workers)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.22", label: "Details of safety incidents - Reportable injuries", type: "textarea", required: true, core: true },
          { id: "C.P3.E.23", label: "Measures taken to ensure safe and healthy workplace", type: "textarea", required: true },
          { id: "C.P3.E.24", label: "Complaints on working conditions/health & safety (current + preceding FY - filed/pending/resolved)", type: "textarea", required: true, core: true },
          { id: "C.P3.E.25", label: "Assessments for the year - % of plants/offices assessed for health & safety", type: "number", required: true },
          { id: "C.P3.L.1", label: "Whether entity provides life insurance/disability and invalidity coverage to employees/workers", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P3.L.2", label: "Transition assistance programs provided to retiring employees", type: "textarea", required: false, leadership: true },
          { id: "C.P3.L.3", label: "High consequence work-related injuries/ill-health (employees/workers)", type: "textarea", required: false, leadership: true },
          { id: "C.P3.L.4", label: "Whether entity provides rehab support for affected employees/workers", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P3.E.26", label: "% of plants/offices assessed for working conditions", type: "number", required: true },
          { id: "C.P3.E.27", label: "Corrective actions taken/underway to address safety-related incidents", type: "textarea", required: true },
          { id: "C.P3.E.28", label: "Processes used to identify work-related hazards and assess risks", type: "textarea", required: true },
          { id: "C.P3.E.29", label: "Whether workers can report work-related hazards and remove themselves from risks (Y/N)", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.30", label: "Whether employees/workers have access to non-occupational medical/healthcare services (Y/N)", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P3.E.31", label: "Complaints on Working Conditions - Filed/Pending/Resolved (current + preceding FY)", type: "textarea", required: true, core: true },
          { id: "C.P3.L.5", label: "Measures undertaken to ensure statutory dues deposited by value chain partners", type: "textarea", required: false, leadership: true },
          { id: "C.P3.L.6", label: "% of value chain partners assessed for health and safety practices", type: "number", required: false, leadership: true },
          { id: "C.P3.L.7", label: "% of value chain partners assessed for working conditions", type: "number", required: false, leadership: true },
          { id: "C.P3.L.8", label: "Corrective actions for significant risks from value chain H&S assessments", type: "textarea", required: false, leadership: true },
        ],
      },
      {
        id: "principle_4",
        name: "P4 — Stakeholder Engagement",
        fields: [
          { id: "C.P4.E.1", label: "Stakeholder group(s) identified as key for the entity", type: "textarea", required: true },
          { id: "C.P4.E.2", label: "Channels/platforms/structure for stakeholder engagement", type: "textarea", required: true },
          { id: "C.P4.L.1", label: "Details of processes for consulting stakeholders on economic/environmental/social topics", type: "textarea", required: false, leadership: true },
          { id: "C.P4.L.2", label: "Whether key stakeholder concerns form part of decision-making", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P4.L.3", label: "Details of engagement with vulnerable/marginalized stakeholder groups", type: "textarea", required: false, leadership: true },
        ],
      },
      {
        id: "principle_5",
        name: "P5 — Human Rights",
        fields: [
          { id: "C.P5.E.1", label: "Employees covered by training on Human Rights issues/policy (% by category)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.2", label: "Workers covered by training on Human Rights issues/policy (% by category)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.3", label: "Details of minimum wages paid - Employees (Equal to/More than min wage by gender)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.4", label: "Details of minimum wages paid - Workers (Equal to/More than min wage by gender)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.5", label: "Details of remuneration/salary/wages - Median remuneration Male vs Female (Board/KMP/Employees/Workers)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.6", label: "Gross wages paid to females as % of total wages (by Board/KMP/Employees/Workers)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.7", label: "Complaints on Sexual Harassment (POSH) - Filed/Pending/Resolved (current + preceding FY)", type: "textarea", required: true },
          { id: "C.P5.E.8", label: "Complaints on Discrimination at workplace - Filed/Pending/Resolved (current + preceding FY)", type: "textarea", required: true },
          { id: "C.P5.E.9", label: "Complaints on Child Labour - Filed/Pending/Resolved (current + preceding FY)", type: "textarea", required: true, core: true },
          { id: "C.P5.E.10", label: "Complaints on Forced Labour/Involuntary Labour - Filed/Pending/Resolved", type: "textarea", required: true, core: true },
          { id: "C.P5.E.11", label: "Complaints on Wages - Filed/Pending/Resolved (current + preceding FY)", type: "textarea", required: true },
          { id: "C.P5.E.12", label: "% of plants/offices assessed for Human Rights (by entity/statutory/third party)", type: "number", required: true },
          { id: "C.P5.E.13", label: "Corrective actions taken/underway to address significant HR risks/concerns", type: "textarea", required: true },
          { id: "C.P5.L.1", label: "Details of business processes modified based on HR due diligence/assessments", type: "textarea", required: false, leadership: true },
          { id: "C.P5.L.2", label: "Details of scope and coverage of Human Rights due diligence (value chain)", type: "textarea", required: false, leadership: true },
          { id: "C.P5.E.14", label: "Whether focal point (Individual/Committee) exists for addressing human rights impacts (Y/N)", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P5.E.15", label: "Internal mechanisms to redress grievances related to human rights issues", type: "textarea", required: true },
          { id: "C.P5.E.16", label: "Complaints on Other human rights issues - Filed/Pending/Resolved", type: "textarea", required: true },
          { id: "C.P5.E.17", label: "POSH complaints as % of female employees/workers", type: "number", required: true },
          { id: "C.P5.E.18", label: "Number of POSH complaints upheld", type: "number", required: true },
          { id: "C.P5.E.19", label: "Mechanisms to prevent adverse consequences to complainant in discrimination/harassment cases", type: "textarea", required: true },
          { id: "C.P5.E.20", label: "Whether human rights requirements form part of business agreements/contracts (Y/N)", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P5.E.21", label: "% of plants/offices assessed for child labour", type: "number", required: true },
          { id: "C.P5.E.22", label: "% of plants/offices assessed for forced/involuntary labour", type: "number", required: true },
          { id: "C.P5.E.23", label: "% of plants/offices assessed for sexual harassment", type: "number", required: true },
          { id: "C.P5.E.24", label: "% of plants/offices assessed for discrimination at workplace", type: "number", required: true },
          { id: "C.P5.E.25", label: "% of plants/offices assessed for wages compliance", type: "number", required: true },
          { id: "C.P5.E.26", label: "Corrective actions from HR assessments (Q10 above)", type: "textarea", required: true },
          { id: "C.P5.L.3", label: "Whether premises accessible to differently abled visitors (Rights of PwD Act 2016)", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P5.L.4", label: "% of value chain partners assessed for sexual harassment", type: "number", required: false, leadership: true },
          { id: "C.P5.L.5", label: "% of value chain partners assessed for discrimination at workplace", type: "number", required: false, leadership: true },
          { id: "C.P5.L.6", label: "% of value chain partners assessed for child labour", type: "number", required: false, leadership: true },
          { id: "C.P5.L.7", label: "% of value chain partners assessed for forced/involuntary labour", type: "number", required: false, leadership: true },
          { id: "C.P5.L.8", label: "% of value chain partners assessed for wages compliance", type: "number", required: false, leadership: true },
          { id: "C.P5.L.9", label: "Corrective actions from value chain HR assessments", type: "textarea", required: false, leadership: true },
        ],
      },
      {
        id: "principle_6",
        name: "P6 — Environmental Protection",
        fields: [
          { id: "C.P6.E.1", label: "Total energy consumption - from renewable sources (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.2", label: "Total energy consumption - from non-renewable sources (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.3", label: "Total electricity consumption (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.4", label: "Total fuel consumption (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.5", label: "Energy intensity per rupee of turnover (GJ/INR cr)", type: "number", required: true, core: true },
          { id: "C.P6.E.6", label: "Whether entity has indicated voluntary target for renewable energy usage", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P6.E.7", label: "Whether entity uses PAT scheme (Perform Achieve Trade)", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P6.E.8", label: "Water withdrawal by source - Surface water (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.9", label: "Water withdrawal by source - Groundwater (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.10", label: "Water withdrawal by source - Third party (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.11", label: "Total volume of water withdrawal (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.12", label: "Total volume of water consumption (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.13", label: "Water intensity per rupee of turnover (KL/INR cr)", type: "number", required: true, core: true },
          { id: "C.P6.E.14", label: "Water discharged by destination and treatment (KL)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.15", label: "Whether water withdrawal from areas of water stress", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P6.E.16", label: "Scope 1 emissions - Total GHG (tCO2e)", type: "number", required: true, core: true },
          { id: "C.P6.E.17", label: "Scope 2 emissions - Total GHG (tCO2e)", type: "number", required: true, core: true },
          { id: "C.P6.E.18", label: "Total Scope 1 and Scope 2 emissions per rupee of turnover (intensity)", type: "number", required: true, core: true },
          { id: "C.P6.E.19", label: "Whether entity has voluntarily set GHG emission reduction target", type: "select", required: true, options: ["Yes", "No"], core: true },
          { id: "C.P6.E.20", label: "Whether project registered under CDM/voluntary mechanism", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P6.E.21", label: "Waste generated - Plastic waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.22", label: "Waste generated - E-waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.23", label: "Waste generated - Bio-medical waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.24", label: "Waste generated - Construction/demolition waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.25", label: "Waste generated - Battery waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.26", label: "Waste generated - Radioactive waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.27", label: "Waste generated - Other Hazardous waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.28", label: "Waste generated - Other Non-hazardous waste (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.29", label: "Total waste generated (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.30", label: "Waste intensity per rupee of turnover (MT/INR cr)", type: "number", required: true, core: true },
          { id: "C.P6.E.31", label: "Each category of waste - Recovered through recycling (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.32", label: "Each category of waste - Recovered through re-using (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.33", label: "Each category of waste - Recovered through other recovery (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.34", label: "Each category of waste - Disposed to landfill (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.35", label: "Each category of waste - Disposed by incineration (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.36", label: "Whether entity has operations in/around ecologically sensitive areas", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P6.E.37", label: "Details of environmental impact assessments (EIAs) undertaken", type: "textarea", required: true },
          { id: "C.P6.E.38", label: "Details of environmental compliance/non-compliances", type: "textarea", required: true },
          { id: "C.P6.L.1", label: "Water discharge - Zero Liquid Discharge status (with breakup)", type: "textarea", required: false, core: true, leadership: true },
          { id: "C.P6.L.2", label: "Scope 3 emissions - Total GHG (tCO2e) with sources", type: "number", required: false, core: true, leadership: true },
          { id: "C.P6.L.3", label: "Whether entity has signed voluntary pledge/agreement for environmental protection", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P6.L.4", label: "Significant direct/indirect impact on biodiversity", type: "textarea", required: false, leadership: true },
          { id: "C.P6.L.5", label: "Whether entity has framework/policy on circular economy", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P6.E.39", label: "Energy consumption through other renewable sources (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.40", label: "Total energy consumed from renewable sources (A+B+C) (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.41", label: "Energy consumption through other non-renewable sources (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.42", label: "Total energy consumed from non-renewable sources (D+E+F) (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.43", label: "Total energy consumed (all sources) (GJ)", type: "number", required: true, core: true },
          { id: "C.P6.E.44", label: "Energy intensity adjusted for Purchasing Power Parity (PPP)", type: "number", required: true, core: true },
          { id: "C.P6.E.45", label: "Energy intensity in terms of physical output", type: "number", required: true },
          { id: "C.P6.E.46", label: "Whether independent assessment of energy data (Y/N) + agency name", type: "textarea", required: true, core: true },
          { id: "C.P6.E.47", label: "PAT Scheme - Whether targets achieved (Y/N) + remedial actions if not", type: "textarea", required: true },
          { id: "C.P6.E.48", label: "Water withdrawal - Seawater/desalinated water (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.49", label: "Water withdrawal - Others (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.50", label: "Water intensity adjusted for Purchasing Power Parity (PPP)", type: "number", required: true, core: true },
          { id: "C.P6.E.51", label: "Water intensity in terms of physical output", type: "number", required: true },
          { id: "C.P6.E.52", label: "Whether independent assessment of water data (Y/N) + agency name", type: "textarea", required: true, core: true },
          { id: "C.P6.E.53", label: "Total water discharged (KL)", type: "number", required: true, core: true },
          { id: "C.P6.E.54", label: "Whether entity has implemented Zero Liquid Discharge (Y/N) + coverage details", type: "textarea", required: true },
          { id: "C.P6.E.55", label: "Air emissions - NOx (specify unit)", type: "number", required: true, core: true },
          { id: "C.P6.E.56", label: "Air emissions - SOx (specify unit)", type: "number", required: true, core: true },
          { id: "C.P6.E.57", label: "Air emissions - Particulate Matter PM (specify unit)", type: "number", required: true, core: true },
          { id: "C.P6.E.58", label: "Air emissions - Persistent Organic Pollutants POP (specify unit)", type: "number", required: true },
          { id: "C.P6.E.59", label: "Air emissions - Volatile Organic Compounds VOC (specify unit)", type: "number", required: true },
          { id: "C.P6.E.60", label: "Air emissions - Hazardous Air Pollutants HAP (specify unit)", type: "number", required: true },
          { id: "C.P6.E.61", label: "Air emissions - Others (specify unit)", type: "number", required: true },
          { id: "C.P6.E.62", label: "Whether independent assessment of air emissions data (Y/N) + agency name", type: "textarea", required: true, core: true },
          { id: "C.P6.E.63", label: "GHG Scope 1+2 intensity adjusted for Purchasing Power Parity (PPP)", type: "number", required: true, core: true },
          { id: "C.P6.E.64", label: "GHG Scope 1+2 intensity in terms of physical output", type: "number", required: true },
          { id: "C.P6.E.65", label: "Whether independent assessment of GHG emissions data (Y/N) + agency name", type: "textarea", required: true, core: true },
          { id: "C.P6.E.66", label: "Details of GHG emission reduction projects (if registered under CDM/voluntary)", type: "textarea", required: true },
          { id: "C.P6.E.67", label: "Waste intensity adjusted for Purchasing Power Parity (PPP)", type: "number", required: true, core: true },
          { id: "C.P6.E.68", label: "Waste intensity in terms of physical output", type: "number", required: true },
          { id: "C.P6.E.69", label: "Each category of waste - Disposed by other disposal operations (MT)", type: "textarea", required: true, core: true },
          { id: "C.P6.E.70", label: "Total waste recovered (recycled + reused + other recovery) (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.71", label: "Total waste disposed (incineration + landfill + other) (MT)", type: "number", required: true, core: true },
          { id: "C.P6.E.72", label: "Whether independent assessment of waste data (Y/N) + agency name", type: "textarea", required: true, core: true },
          { id: "C.P6.E.73", label: "Waste management practices adopted + strategy to reduce hazardous/toxic chemicals", type: "textarea", required: true },
          { id: "C.P6.E.74", label: "Details of operations in ecologically sensitive areas - Location/Type/Compliance status", type: "textarea", required: true },
          { id: "C.P6.E.75", label: "Whether entity compliant with Water Act, Air Act, EP Act (Y/N) + non-compliance details", type: "textarea", required: true },
          { id: "C.P6.L.6", label: "Water withdrawal/consumption/discharge in areas of water stress (detailed by facility)", type: "textarea", required: false, core: true, leadership: true },
          { id: "C.P6.L.7", label: "Scope 3 emissions intensity per rupee of turnover", type: "number", required: false, core: true, leadership: true },
          { id: "C.P6.L.8", label: "Scope 3 emissions intensity (optional metric selected by entity)", type: "number", required: false, leadership: true },
          { id: "C.P6.L.9", label: "Whether independent assessment of Scope 3 data (Y/N) + agency name", type: "textarea", required: false, core: true, leadership: true },
          { id: "C.P6.L.10", label: "Significant direct/indirect impact on biodiversity - prevention and remediation activities", type: "textarea", required: false, leadership: true },
          { id: "C.P6.L.11", label: "Initiatives/innovative technology to improve resource efficiency or reduce emissions/waste", type: "textarea", required: false, leadership: true },
          { id: "C.P6.L.12", label: "Whether entity has business continuity and disaster management plan (details/web link)", type: "textarea", required: false, leadership: true },
          { id: "C.P6.L.13", label: "Significant adverse environmental impact from value chain + mitigation/adaptation measures", type: "textarea", required: false, leadership: true },
          { id: "C.P6.L.14", label: "% of value chain partners assessed for environmental impacts", type: "number", required: false, leadership: true },
        ],
      },
      {
        id: "principle_7",
        name: "P7 — Policy Advocacy",
        fields: [
          { id: "C.P7.E.1", label: "Trade and industry chambers/associations entity is member of (top 10 by fees)", type: "textarea", required: true },
          { id: "C.P7.E.2", label: "Details of cases of anti-competitive conduct by entity (past 5 years)", type: "textarea", required: true },
          { id: "C.P7.L.1", label: "Public policy advocacy positions - top issues and entity's position", type: "textarea", required: false, leadership: true },
          { id: "C.P7.E.3", label: "Number of affiliations with trade and industry chambers/associations", type: "number", required: true },
          { id: "C.P7.E.4", label: "Corrective action on anti-competitive conduct (from adverse orders)", type: "textarea", required: true },
        ],
      },
      {
        id: "principle_8",
        name: "P8 — Inclusive Growth",
        fields: [
          { id: "C.P8.E.1", label: "Details of Social Impact Assessments (SIA) - Name/Date/Results/External agency", type: "textarea", required: true },
          { id: "C.P8.E.2", label: "Details of rehabilitation and resettlement - project name/affected families/amount paid", type: "textarea", required: true },
          { id: "C.P8.E.3", label: "Whether entity has mechanisms to receive/redress community grievances", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P8.E.4", label: "Community complaints/grievances - Number received and pending resolution (%)", type: "textarea", required: true },
          { id: "C.P8.E.5", label: "Percentage of input material sourced from MSMEs/small producers", type: "number", required: true, core: true },
          { id: "C.P8.E.6", label: "Percentage of input material sourced from within district/neighbouring districts", type: "number", required: true, core: true },
          { id: "C.P8.E.7", label: "Details of CSR projects - Amount spent/allocated/unspent", type: "textarea", required: true },
          { id: "C.P8.L.1", label: "Job creation in smaller towns - Wages paid to persons employed in smaller towns", type: "textarea", required: false, leadership: true },
          { id: "C.P8.L.2", label: "Whether entity has beneficial impact on local community (aspiration districts)", type: "textarea", required: false, leadership: true },
          { id: "C.P8.L.3", label: "Preferential procurement policy for marginalized/vulnerable groups", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P8.L.4", label: "CSR beneficiaries breakdown by SC/ST/Others", type: "textarea", required: false, leadership: true },
          { id: "C.P8.E.8", label: "Job creation in smaller towns - wages paid (Rural/Semi-urban/Urban/Metro as % of total)", type: "textarea", required: true },
          { id: "C.P8.L.5", label: "Actions taken to mitigate negative social impacts from SIAs", type: "textarea", required: false, leadership: true },
          { id: "C.P8.L.6", label: "CSR projects in aspirational districts (State/District/Amount spent)", type: "textarea", required: false, leadership: true },
          { id: "C.P8.L.7", label: "Details of benefits from intellectual properties based on traditional knowledge", type: "textarea", required: false, leadership: true },
          { id: "C.P8.L.8", label: "Corrective actions on adverse orders in IP disputes involving traditional knowledge", type: "textarea", required: false, leadership: true },
        ],
      },
      {
        id: "principle_9",
        name: "P9 — Consumer Responsibility",
        fields: [
          { id: "C.P9.E.1", label: "Complaints on Data Privacy - Number received/pending/remarks (current + preceding FY)", type: "textarea", required: true, core: true },
          { id: "C.P9.E.2", label: "Complaints on Advertising - Number received/pending/remarks (current + preceding FY)", type: "textarea", required: true, core: true },
          { id: "C.P9.E.3", label: "Complaints on Cyber-Security - Number received/pending/remarks", type: "textarea", required: true, core: true },
          { id: "C.P9.E.4", label: "Complaints on Delivery of essential services - Number received/pending/remarks", type: "textarea", required: true, core: true },
          { id: "C.P9.E.5", label: "Complaints on Restrictive Trade Practices - Number received/pending/remarks", type: "textarea", required: true, core: true },
          { id: "C.P9.E.6", label: "Complaints on Unfair Trade Practices - Number received/pending/remarks", type: "textarea", required: true, core: true },
          { id: "C.P9.E.7", label: "Number of instances of product recalls - voluntary/forced (current + preceding FY)", type: "textarea", required: true, core: true },
          { id: "C.P9.E.8", label: "Reasons for each product recall", type: "textarea", required: true, core: true },
          { id: "C.P9.E.9", label: "Whether entity has a framework/policy on cyber security and data privacy", type: "select", required: true, options: ["Yes", "No"] },
          { id: "C.P9.E.10", label: "Details of corrective actions taken/underway on issues related to product/service quality", type: "textarea", required: true },
          { id: "C.P9.L.1", label: "Whether entity provides information on environmental/social parameters of products to consumers", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P9.L.2", label: "Whether entity conducts consumer surveys/feedback mechanisms", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P9.L.3", label: "Turnover from products/services incorporating social/environmental risks/concerns (%)", type: "number", required: false, leadership: true },
          { id: "C.P9.E.11", label: "Mechanisms in place to receive and respond to consumer complaints/feedback (description)", type: "textarea", required: true },
          { id: "C.P9.E.12", label: "Turnover from products carrying environmental/social parameters info (%)", type: "number", required: true },
          { id: "C.P9.E.13", label: "Turnover from products carrying safe/responsible usage info (%)", type: "number", required: true },
          { id: "C.P9.E.14", label: "Turnover from products carrying recycling/safe disposal info (%)", type: "number", required: true },
          { id: "C.P9.E.15", label: "Corrective actions on advertising/delivery of essential services issues", type: "textarea", required: true },
          { id: "C.P9.E.16", label: "Corrective actions on cyber security and data privacy issues", type: "textarea", required: true },
          { id: "C.P9.E.17", label: "Corrective actions on re-occurrence of product recalls", type: "textarea", required: true },
          { id: "C.P9.E.18", label: "Corrective actions on penalty/action by regulatory authorities on product safety", type: "textarea", required: true },
          { id: "C.P9.E.19", label: "Number of instances of data breaches", type: "number", required: true, core: true },
          { id: "C.P9.E.20", label: "% of data breaches involving personally identifiable information of customers", type: "number", required: true, core: true },
          { id: "C.P9.E.21", label: "Impact of data breaches (description)", type: "textarea", required: true, core: true },
          { id: "C.P9.L.4", label: "Steps taken to inform/educate consumers about safe and responsible usage of products", type: "textarea", required: false, leadership: true },
          { id: "C.P9.L.5", label: "Mechanisms to inform consumers of risk of disruption/discontinuation of essential services", type: "textarea", required: false, leadership: true },
          { id: "C.P9.L.6", label: "Whether entity displays product information beyond what is mandated by local laws (Y/N)", type: "select", required: false, options: ["Yes", "No"], leadership: true },
          { id: "C.P9.L.7", label: "Whether consumer satisfaction survey conducted (Y/N) + details", type: "textarea", required: false, leadership: true },
          { id: "C.P9.L.8", label: "Channels/platforms where products/services info can be accessed (web link)", type: "textarea", required: false, leadership: true },
        ],
      },
    ],
  },
};

export const TOTAL_DATAPOINTS = 337;
export const MANDATORY_DATAPOINTS = 276;
export const CORE_DATAPOINTS = 121;
export const LEADERSHIP_DATAPOINTS = 58;

