import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Terms of Use — FileBRSR",
  description: "Terms and conditions for using the FileBRSR platform.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-1 py-20 px-6" style={{ background: "#FAFAFA" }}>
        <div className="max-w-3xl mx-auto bg-white rounded-2xl border border-gray-200 p-8 md:p-12">
          <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
          <p className="text-sm text-gray-400 mb-8">Last updated: 24 May 2026</p>

          <div className="prose prose-sm prose-gray max-w-none space-y-6">
            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">1. Acceptance of Terms</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                By accessing or using FileBRSR (&quot;Platform&quot;, &quot;we&quot;, &quot;us&quot;), you agree to be bound by these Terms of Use. If you do not agree, please do not use the Platform.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">2. Description of Service</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                FileBRSR provides AI-powered BRSR (Business Responsibility and Sustainability Reporting) compliance tools, including but not limited to: automated data extraction from annual reports, BRSR report generation, supply chain ESG assessments, carbon emission calculations, and regulatory compliance tracking for SEBI-mandated disclosures.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">3. User Accounts</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                You must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You must notify us immediately of any unauthorized use.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">4. Acceptable Use</h2>
              <p className="text-sm text-gray-600 leading-relaxed">You agree not to:</p>
              <ul className="list-disc pl-5 text-sm text-gray-600 space-y-1 mt-2">
                <li>Use the Platform for any unlawful purpose or in violation of any applicable regulations</li>
                <li>Upload malicious files, viruses, or harmful code</li>
                <li>Attempt to gain unauthorized access to our systems or other users&apos; accounts</li>
                <li>Scrape, crawl, or use automated tools to extract data from the Platform without written consent</li>
                <li>Resell, sublicense, or redistribute reports generated by the Platform without authorization</li>
                <li>Misrepresent AI-generated reports as certified auditor opinions</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">5. Intellectual Property</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                The Platform, including its AI models, algorithms, UI design, branding, and documentation, is the intellectual property of FileBRSR. You retain ownership of data you upload. By uploading content, you grant us a limited license to process it solely for providing our services to you.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">6. AI-Generated Content Disclaimer</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                Reports and extractions generated by our AI are intended as decision-support tools. They do not constitute legal, financial, or auditing advice. Users are responsible for reviewing and validating AI outputs before submission to regulatory authorities (SEBI, BSE, NSE). We recommend engaging a qualified auditor for final BRSR filings.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">7. Payment & Subscriptions</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                Paid plans are billed in advance on a monthly or annual basis. All fees are in Indian Rupees (INR) and exclusive of applicable GST. Refunds are provided only if the Platform is materially unavailable for more than 72 consecutive hours during your billing period.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">8. Data Security</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                We implement industry-standard security measures including encryption at rest and in transit, role-based access controls, and regular security audits. Data is stored in secure cloud infrastructure within India (AWS Mumbai region). See our Privacy Policy for details on data handling.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">9. Limitation of Liability</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                To the maximum extent permitted by law, FileBRSR shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities arising from your use of the Platform. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">10. Termination</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                We may suspend or terminate your access if you violate these Terms. Upon termination, your right to use the Platform ceases immediately. You may export your data within 30 days of termination notice. After 30 days, we may delete your data.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">11. Governing Law</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in India.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">12. Changes to Terms</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                We may update these Terms from time to time. We will notify registered users of material changes via email at least 14 days before they take effect. Continued use after changes constitutes acceptance.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold mt-6 mb-2">13. Contact</h2>
              <p className="text-sm text-gray-600 leading-relaxed">
                For questions about these Terms, contact us at:<br />
                <strong>Email:</strong> support@filebrsr.com<br />
                <strong>Website:</strong> filebrsr.com
              </p>
            </section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
