"""
Excel Bulk Import — Parse filled BRSR data from Excel and upsert into brsr_entries.

Accepts the template generated by generate_datapoints_excel.py (or any Excel with
columns: datapoint_id, value, evidence, source_document).
"""

import io
from typing import Optional
from datetime import datetime

from fastapi import APIRouter, UploadFile, File, Form, HTTPException, Header
from openpyxl import load_workbook

from app.config import get_settings
from app.brsr_datapoints import BRSR_DATAPOINTS

router = APIRouter(prefix="/api/v2", tags=["Excel Import"])
settings = get_settings()

VALID_DATAPOINT_IDS = {dp["id"] for dp in BRSR_DATAPOINTS}


def get_supabase_admin():
    from supabase import create_client
    return create_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_KEY)


async def get_user_id(authorization: str) -> str:
    token = authorization.replace("Bearer ", "")
    if not token:
        raise HTTPException(status_code=401, detail="Missing auth token")
    try:
        import jwt as pyjwt
        payload = pyjwt.decode(token, options={"verify_signature": False})
        return payload.get("sub", token)
    except Exception:
        return token


@router.post("/import-excel")
async def import_excel(
    file: UploadFile = File(...),
    financial_year: str = Form("FY2024-25"),
    overwrite: bool = Form(False),
    authorization: str = Header(...),
):
    """
    Import BRSR data from a filled Excel workbook.

    Expected format (any sheet):
    - Column A or header 'datapoint_id' / 'id' / 'ID': BRSR datapoint ID (e.g. A.I.1)
    - Column with header 'value' / 'Value' / 'data': The reported value
    - Column with header 'evidence' / 'Evidence' (optional): Supporting evidence
    - Column with header 'source' / 'Source Document' (optional): Source reference

    Returns: count of imported entries, skipped entries, and any errors.
    """
    user_id = await get_user_id(authorization)

    # Validate file type
    if not file.filename or not file.filename.endswith((".xlsx", ".xls")):
        raise HTTPException(status_code=400, detail="Only .xlsx or .xls files are accepted")

    # Read file
    content = await file.read()
    if len(content) > 10 * 1024 * 1024:  # 10MB limit
        raise HTTPException(status_code=400, detail="File too large. Maximum 10MB.")

    try:
        wb = load_workbook(io.BytesIO(content), read_only=True, data_only=True)
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Cannot read Excel file: {str(e)}")

    # Find data across all sheets
    entries = []
    errors = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows:
            continue

        # Find header row (first row with recognizable column names)
        header_row = None
        header_idx = 0
        for i, row in enumerate(rows[:5]):  # Check first 5 rows for headers
            row_lower = [str(c).lower().strip() if c else "" for c in row]
            if any(h in row_lower for h in ["datapoint_id", "id", "data point id", "dp id"]):
                header_row = row_lower
                header_idx = i
                break

        if not header_row:
            # Try column A as ID if it looks like datapoint IDs
            if rows[0] and rows[1]:
                first_val = str(rows[1][0]) if rows[1][0] else ""
                if "." in first_val and first_val.split(".")[0] in ("A", "B", "C"):
                    # Assume: Col A = ID, Col B = label, Col C = value
                    header_row = ["id", "label", "value", "evidence", "source"]
                    header_idx = 0
                else:
                    continue
            else:
                continue

        # Map column indices
        id_col = None
        value_col = None
        evidence_col = None
        source_col = None

        for idx, h in enumerate(header_row):
            if h in ("datapoint_id", "id", "data point id", "dp id", "datapoint id"):
                id_col = idx
            elif h in ("value", "data", "reported value", "current year", "fy value"):
                value_col = idx
            elif h in ("evidence", "supporting evidence", "notes", "remarks"):
                evidence_col = idx
            elif h in ("source", "source document", "source_document", "document"):
                source_col = idx

        if id_col is None:
            id_col = 0
        if value_col is None:
            value_col = 2 if len(header_row) > 2 else 1

        # Parse data rows
        for row_num, row in enumerate(rows[header_idx + 1:], start=header_idx + 2):
            if not row or not row[id_col]:
                continue

            dp_id = str(row[id_col]).strip()

            # Normalize ID format (handle "A.I.1" or "A_I_1" or "AI1")
            dp_id = dp_id.replace("_", ".").upper()

            if dp_id not in VALID_DATAPOINT_IDS:
                # Try prefix matching for common formats
                if not any(c == "." for c in dp_id):
                    continue
                errors.append({"row": row_num, "sheet": sheet_name, "id": dp_id, "error": "Unknown datapoint ID"})
                continue

            value = row[value_col] if value_col < len(row) else None
            if value is None or str(value).strip() == "":
                continue  # Skip empty values

            value_str = str(value).strip()

            evidence = ""
            if evidence_col and evidence_col < len(row) and row[evidence_col]:
                evidence = str(row[evidence_col]).strip()

            source = ""
            if source_col and source_col < len(row) and row[source_col]:
                source = str(row[source_col]).strip()

            entries.append({
                "datapoint_id": dp_id,
                "value": value_str,
                "evidence": evidence,
                "source_document": source,
                "sheet": sheet_name,
            })

    wb.close()

    if not entries:
        raise HTTPException(status_code=400, detail="No valid data found in the Excel file. Ensure column headers include 'datapoint_id' and 'value'.")

    # Upsert into brsr_entries
    sb = get_supabase_admin()
    imported = 0
    skipped = 0

    for entry in entries:
        try:
            row_data = {
                "user_id": user_id,
                "datapoint_id": entry["datapoint_id"],
                "financial_year": financial_year,
                "value": entry["value"],
                "status": "imported",
                "updated_at": datetime.utcnow().isoformat(),
            }

            if entry["evidence"]:
                row_data["evidence"] = entry["evidence"]
            if entry["source_document"]:
                row_data["source_document"] = entry["source_document"]

            if overwrite:
                sb.table("brsr_entries").upsert(
                    row_data,
                    on_conflict="user_id,datapoint_id,financial_year"
                ).execute()
                imported += 1
            else:
                # Check if entry already exists
                existing = sb.table("brsr_entries").select("id").eq(
                    "user_id", user_id
                ).eq("datapoint_id", entry["datapoint_id"]).eq(
                    "financial_year", financial_year
                ).execute()

                if existing.data:
                    skipped += 1
                else:
                    sb.table("brsr_entries").insert(row_data).execute()
                    imported += 1

        except Exception as e:
            errors.append({
                "datapoint_id": entry["datapoint_id"],
                "error": str(e)[:100],
            })

    return {
        "status": "success",
        "imported": imported,
        "skipped": skipped,
        "errors": errors[:20],  # Limit error output
        "total_parsed": len(entries),
        "financial_year": financial_year,
    }


@router.get("/import-excel/template")
async def get_import_template():
    """
    Download a pre-formatted Excel template for bulk data import.
    Contains all 337 BRSR datapoints with columns ready to fill.
    """
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from fastapi.responses import StreamingResponse

    wb = Workbook()

    # Group by section
    sections = {}
    for dp in BRSR_DATAPOINTS:
        sec = dp.get("section", "other")
        if sec not in sections:
            sections[sec] = []
        sections[sec].append(dp)

    first = True
    for section, datapoints in sections.items():
        if first:
            ws = wb.active
            ws.title = section.replace("_", " ").title()[:31]
            first = False
        else:
            ws = wb.create_sheet(title=section.replace("_", " ").title()[:31])

        # Headers
        headers = ["Datapoint ID", "Label", "Value", "Evidence / Notes", "Source Document", "Mandatory", "Core (BRSR Core)"]
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="1B5E20", end_color="1B5E20", fill_type="solid")

        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=h)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center")

        # Data rows
        for row_num, dp in enumerate(datapoints, 2):
            ws.cell(row=row_num, column=1, value=dp["id"])
            ws.cell(row=row_num, column=2, value=dp["label"])
            ws.cell(row=row_num, column=3, value="")  # Value — to be filled
            ws.cell(row=row_num, column=4, value="")  # Evidence
            ws.cell(row=row_num, column=5, value="")  # Source
            ws.cell(row=row_num, column=6, value="Yes" if dp.get("mandatory") else "No")
            ws.cell(row=row_num, column=7, value="Yes" if dp.get("core") else "No")

        # Column widths
        ws.column_dimensions["A"].width = 14
        ws.column_dimensions["B"].width = 50
        ws.column_dimensions["C"].width = 40
        ws.column_dimensions["D"].width = 30
        ws.column_dimensions["E"].width = 25
        ws.column_dimensions["F"].width = 12
        ws.column_dimensions["G"].width = 14

    output = io.BytesIO()
    wb.save(output)
    output.seek(0)

    return StreamingResponse(
        output,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": "attachment; filename=brsr_import_template.xlsx"},
    )
