"""
PDF Compliance Report Generator for FileBRSR.
Generates branded PDF reports with:
- Compliance score summary
- Section-wise gap analysis
- NIFTY 50 benchmark comparison
- Prioritized recommendations
"""
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT


# Brand colors
PRIMARY = colors.HexColor("#1B4D3E")
PRIMARY_LIGHT = colors.HexColor("#2D7A5F")
ACCENT = colors.HexColor("#E8B931")
MUTED = colors.HexColor("#6B7280")
BG_LIGHT = colors.HexColor("#F0FDF4")
RED = colors.HexColor("#DC2626")
GREEN = colors.HexColor("#16A34A")
ORANGE = colors.HexColor("#EA580C")


def generate_compliance_pdf(
    extracted_data: dict,
    gap_analysis: dict,
    benchmark: dict,
    company_name: str = "Company",
    financial_year: str = "FY 2024-25",
) -> bytes:
    """Generate a branded PDF compliance report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2 * cm,
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    styles.add(ParagraphStyle(
        "BrandTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        textColor=PRIMARY,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "BrandSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=12,
        textColor=MUTED,
        spaceAfter=20,
    ))
    styles.add(ParagraphStyle(
        "SectionHead",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=16,
        textColor=PRIMARY,
        spaceBefore=20,
        spaceAfter=10,
    ))
    styles.add(ParagraphStyle(
        "SubHead",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=12,
        textColor=PRIMARY_LIGHT,
        spaceBefore=12,
        spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        "BrandBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        textColor=colors.HexColor("#374151"),
        spaceAfter=6,
        leading=14,
    ))
    styles.add(ParagraphStyle(
        "SmallMuted",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        textColor=MUTED,
    ))
    
    elements = []
    
    # ═══ COVER PAGE ═══
    elements.append(Spacer(1, 3 * cm))
    elements.append(Paragraph("FileBRSR", styles["BrandTitle"]))
    elements.append(Paragraph("BRSR Compliance Assessment Report", styles["BrandSubtitle"]))
    elements.append(Spacer(1, 1 * cm))
    elements.append(HRFlowable(width="100%", thickness=2, color=PRIMARY))
    elements.append(Spacer(1, 1 * cm))
    
    cover_data = [
        ["Company", company_name],
        ["Financial Year", financial_year],
        ["Report Generated", datetime.now().strftime("%d %B %Y")],
        ["Framework", "SEBI BRSR (Business Responsibility & Sustainability Reporting)"],
        ["Benchmark", f"NIFTY 50 - {benchmark.get('sector', 'General')}"],
    ]
    cover_table = Table(cover_data, colWidths=[4 * cm, 12 * cm])
    cover_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("TEXTCOLOR", (0, 0), (0, -1), PRIMARY),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#1F2937")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#E5E7EB")),
    ]))
    elements.append(cover_table)
    
    elements.append(Spacer(1, 2 * cm))
    elements.append(Paragraph(
        "This report is generated by FileBRSR's AI-powered compliance engine. "
        "It assesses your BRSR disclosure against SEBI requirements and provides "
        "benchmarks against NIFTY 50 peers in your sector.",
        styles["BrandBody"]
    ))
    elements.append(Spacer(1, 1 * cm))
    elements.append(Paragraph(
        "CONFIDENTIAL — For internal compliance use only",
        ParagraphStyle("Conf", parent=styles["Normal"], fontSize=9, textColor=RED, alignment=TA_CENTER)
    ))
    
    elements.append(PageBreak())
    
    # ═══ EXECUTIVE SUMMARY ═══
    elements.append(Paragraph("Executive Summary", styles["SectionHead"]))
    
    # Compliance scores
    total_fields = gap_analysis.get("total_fields", gap_analysis.get("total_datapoints", 216))
    disclosed = gap_analysis.get("fields_found", gap_analysis.get("disclosed_count", 0))
    missing = gap_analysis.get("fields_missing", gap_analysis.get("missing_count", 0))
    score_pct = round((disclosed / total_fields) * 100) if total_fields > 0 else 0
    
    # Determine verdict
    if score_pct >= 85:
        verdict = "STRONG COMPLIANCE"
        verdict_color = GREEN
        verdict_desc = "Your BRSR disclosure meets or exceeds SEBI requirements."
    elif score_pct >= 60:
        verdict = "PARTIAL COMPLIANCE"
        verdict_color = ORANGE
        verdict_desc = "Your disclosure has gaps that need attention before filing."
    else:
        verdict = "SIGNIFICANT GAPS"
        verdict_color = RED
        verdict_desc = "Major disclosures are missing. Immediate action required."
    
    elements.append(Paragraph(f"Overall Compliance Score: {score_pct}%", ParagraphStyle(
        "Score", parent=styles["Normal"], fontSize=18, fontName="Helvetica-Bold", textColor=verdict_color
    )))
    elements.append(Paragraph(f"Verdict: {verdict}", ParagraphStyle(
        "Verdict", parent=styles["Normal"], fontSize=14, fontName="Helvetica-Bold", textColor=verdict_color, spaceAfter=8
    )))
    elements.append(Paragraph(verdict_desc, styles["BrandBody"]))
    elements.append(Spacer(1, 0.5 * cm))
    
    summary_data = [
        ["Metric", "Value"],
        ["Total Data Points (SEBI BRSR)", str(total_fields)],
        ["Disclosed", str(disclosed)],
        ["Missing/Gaps", str(missing)],
        ["Compliance %", f"{score_pct}%"],
        ["Sector Benchmark (Typical)", f"{benchmark.get('typical_disclosure_rate', 80)}%"],
    ]
    summary_table = Table(summary_data, colWidths=[8 * cm, 8 * cm])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (1, 0), (1, -1), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
    ]))
    elements.append(summary_table)
    
    elements.append(PageBreak())
    
    # ═══ NIFTY 50 BENCHMARK COMPARISON ═══
    elements.append(Paragraph("NIFTY 50 Sector Benchmark Comparison", styles["SectionHead"]))
    elements.append(Paragraph(
        f"Your report is compared against the {benchmark.get('sector', 'General')} sector "
        f"({', '.join(benchmark.get('sector_companies', [])[:3])}, etc.)",
        styles["BrandBody"]
    ))
    elements.append(Spacer(1, 0.3 * cm))
    
    bench_metrics = benchmark.get("metrics", {})
    if bench_metrics:
        bench_data = [["Metric", "Your Value", "Sector Median", "Top Quartile", "Status"]]
        for key, m in bench_metrics.items():
            status = m.get("status", "not_disclosed")
            status_display = {
                "top_quartile": "★ Top Quartile",
                "above_median": "✓ Above Median",
                "below_median": "⚠ Below Median",
                "not_disclosed": "— Not Disclosed",
            }.get(status, status)
            
            your_val = str(m.get("your_value", "—")) if m.get("your_value") is not None else "—"
            bench_data.append([
                key.replace("_", " ").title(),
                f"{your_val} {m.get('unit', '')}",
                f"{m['benchmark_median']} {m.get('unit', '')}",
                f"{m['benchmark_top_quartile']} {m.get('unit', '')}",
                status_display,
            ])
        
        bench_table = Table(bench_data, colWidths=[3.5 * cm, 3 * cm, 3 * cm, 3 * cm, 3.5 * cm])
        bench_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("ALIGN", (1, 0), (-1, -1), "CENTER"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
        ]))
        elements.append(bench_table)
    
    elements.append(PageBreak())
    
    # ═══ GAP ANALYSIS ═══
    elements.append(Paragraph("Gap Analysis — Missing Disclosures", styles["SectionHead"]))
    elements.append(Paragraph(
        "The following data points are required by SEBI but were not found in your report. "
        "Priority is determined by: mandatory status, core indicator classification, and ESRS cross-reference.",
        styles["BrandBody"]
    ))
    elements.append(Spacer(1, 0.3 * cm))
    
    missing_items = gap_analysis.get("missing_mandatory", gap_analysis.get("missing", []))
    if missing_items:
        # Show top 30 most critical gaps
        critical_gaps = [g for g in missing_items if g.get("mandatory", True)][:30]
        
        gap_data = [["#", "Data Point", "Section", "Priority", "ESRS Ref"]]
        for i, gap in enumerate(critical_gaps, 1):
            priority = "HIGH" if gap.get("mandatory") and gap.get("core") else "MEDIUM" if gap.get("mandatory") else "LOW"
            gap_data.append([
                str(i),
                (gap.get("label") or gap.get("id") or "Unknown")[:50],
                (gap.get("section") or "—")[:15],
                priority,
                (gap.get("esrs_ref") or "—")[:12],
            ])
        
        gap_table = Table(gap_data, colWidths=[1 * cm, 7 * cm, 3 * cm, 2.5 * cm, 2.5 * cm])
        gap_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, BG_LIGHT]),
        ]))
        elements.append(gap_table)
        
        if len(missing_items) > 30:
            elements.append(Spacer(1, 0.3 * cm))
            elements.append(Paragraph(
                f"... and {len(missing_items) - 30} more gaps. See full list in your FileBRSR dashboard.",
                styles["SmallMuted"]
            ))
    else:
        elements.append(Paragraph("No critical gaps identified. Well done!", styles["BrandBody"]))
    
    elements.append(PageBreak())
    
    # ═══ RECOMMENDATIONS ═══
    elements.append(Paragraph("Priority Recommendations", styles["SectionHead"]))
    
    recommendations = _generate_recommendations(gap_analysis, benchmark, score_pct)
    for i, rec in enumerate(recommendations, 1):
        elements.append(Paragraph(f"{i}. {rec['title']}", styles["SubHead"]))
        elements.append(Paragraph(rec["description"], styles["BrandBody"]))
        elements.append(Spacer(1, 0.2 * cm))
    
    elements.append(Spacer(1, 1 * cm))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    elements.append(Spacer(1, 0.5 * cm))
    elements.append(Paragraph(
        f"Report generated by FileBRSR (filebrsr.com) on {datetime.now().strftime('%d %B %Y at %H:%M')}. "
        "This is an automated assessment and should be reviewed by compliance professionals before filing.",
        styles["SmallMuted"]
    ))
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer.read()


def _generate_recommendations(gap_analysis: dict, benchmark: dict, score_pct: int) -> list[dict]:
    """Generate prioritized recommendations based on gaps and benchmarks."""
    recs = []
    
    missing = gap_analysis.get("missing_mandatory", gap_analysis.get("missing", []))
    bench_metrics = benchmark.get("metrics", {})
    
    # Rec 1: Overall compliance
    if score_pct < 60:
        recs.append({
            "title": "Critical: Comprehensive disclosure overhaul needed",
            "description": f"Your compliance score ({score_pct}%) is significantly below the sector average "
                          f"({benchmark.get('typical_disclosure_rate', 80)}%). Focus on completing all mandatory "
                          "Section A disclosures first, then address Section C principle-wise gaps.",
        })
    elif score_pct < 85:
        recs.append({
            "title": "Fill mandatory disclosure gaps",
            "description": f"Your report is {100 - score_pct}% short of full compliance. "
                          "Focus on the HIGH priority items in the gap analysis table above.",
        })
    
    # Rec 2: Environment (P6)
    p6_missing = [g for g in missing if "p6" in g.get("id", "").lower() or "energy" in g.get("label", "").lower() or "emission" in g.get("label", "").lower()]
    if p6_missing:
        recs.append({
            "title": "Strengthen environmental disclosures (Principle 6)",
            "description": f"{len(p6_missing)} environmental data points are missing including energy consumption, "
                          "GHG emissions, and water data. These are mandatory under BRSR Core and subject to "
                          "third-party assurance from FY 2026-27.",
        })
    
    # Rec 3: Benchmark gaps
    below_median = [k for k, m in bench_metrics.items() if m.get("status") == "below_median"]
    if below_median:
        recs.append({
            "title": "Improve metrics below sector median",
            "description": f"Your company is below the NIFTY 50 sector median for: "
                          f"{', '.join(k.replace('_', ' ').title() for k in below_median[:5])}. "
                          "Consider these areas for improvement initiatives.",
        })
    
    # Rec 4: Not disclosed metrics
    not_disclosed = [k for k, m in bench_metrics.items() if m.get("status") == "not_disclosed"]
    if not_disclosed:
        recs.append({
            "title": "Disclose benchmarkable metrics",
            "description": f"{len(not_disclosed)} key metrics that NIFTY 50 peers typically disclose are missing from "
                          f"your report: {', '.join(k.replace('_', ' ').title() for k in not_disclosed[:5])}. "
                          "Disclosing these will improve comparability with peers.",
        })
    
    # Rec 5: ESRS readiness
    esrs_gaps = [g for g in missing if g.get("esrs_ref")]
    if esrs_gaps:
        recs.append({
            "title": "Prepare for ESRS/ISSB convergence",
            "description": f"{len(esrs_gaps)} of your gaps have ESRS cross-references. As SEBI aligns BRSR with "
                          "global standards (ISSB/ESRS), addressing these now will ease future compliance.",
        })
    
    # Rec 6: Value chain
    recs.append({
        "title": "Plan for value chain BRSR extension",
        "description": "SEBI is extending BRSR disclosures to top-listed companies' value chains. "
                      "Begin collecting supply chain ESG data proactively — this gives 12-18 months lead time.",
    })
    
    return recs[:6]
